config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admin', skip: :registrations
  devise_for :customers,
             path: 'customer',
             controllers: {
               sessions: 'customer/sessions',
               registrations: 'customer/registrations',
               confirmations: 'customer/confirmations'
             }
  devise_for :partners,
             path: 'partner',
             controllers: {
               sessions: 'partner/sessions',
               registrations: 'partner/registrations',
               confirmations: 'partner/confirmations'
             }

  root 'landing#index'
  get 'privacy', to: 'landing#privacy'
  namespace :btrips do
    get '/', to: 'services#index'
    get '/thanks', to: 'services#thanks'
    resources :tailoreds, only: [:index, :create, :new]
    resources :yolos, only: [:index, :create, :new, :update] do
      get '/confirm', to: 'yolos#confirm'
    end
    get 'yolos/calc_estimated', to: 'yolos#calc_estimated'
  end

  namespace :customer do
    scope ':customer_id' do
      get '/', to: 'dashboard#home'
      resources :btrips do
      end
    end
  end

  namespace :partner do
    scope ':partner_id' do
      get '/', to: 'dashboard#home'
    end
  end

  namespace :admin do
    scope ':admin_id' do
      get '/', to: 'dashboard#home'
    end
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin
  class DashboardController < BaseController
    layout 'admin'

    def home
      @tailoreds = Tailored.all
      @yolos = Yolo.all
    end
  end
end

app/controllers/customer/dashboard_controller.rb
class Customer
  class DashboardController < BaseController
    def home
    end
  end
end

app/controllers/partner/dashboard_controller.rb
class Partner
  class DashboardController < BaseController
    def home
    end
  end
end

app/views/admin/dashboard/partials/_content.html.haml
.content-wrapper
  %section.content-header
  %section.content.tab-content
    #admin_content.tab-pane.fade.in.active{ role: "tabpanel" }
      .row
        .col-sm-12
          .callout.callout-warning
            %h4 Registros
            %p Detalles de usuarios registrados.
      .row
        .col-sm-12
          .box.box-success
            .box-header
              %h3.box-title
                %strong
                  %i.fa.fa-user-plus
                  Usuarios registrados
            / /.box-header
            .box-body.table-responsive
              %table#usuarios.table.table-bordered.table-striped
                %thead
                  %tr.boxtrip-success
                    %th ID
                    %th Nombre
                    %th Correo electrónico
                    %th Teléfono
                    %th Tipo de servicio
                %tbody
                  - @tailoreds.each do |tailored|
                    - customer = tailored.customer_info
                    %tr
                      %td= customer.id
                      %td= customer.full_name
                      %td= customer.email
                      %td= customer.phone_number
                      %td TAILORED
                  - @yolos.each do |yolo|
                    - customer = yolo.customer_info
                    %tr
                      %td= customer.id
                      %td= customer.full_name
                      %td= customer.email
                      %td= customer.phone_number
                      %td YOLO

app/views/admin/dashboard/partials/_footer.html.haml
%footer.main-footer
  / Default to the left
  %strong
    Copyright © 2015
    %a{:href => "#"} RandomWalker
  All rights reserved.

app/views/admin/dashboard/partials/_header.html.haml
%header.main-header
  / Logo
  %a.logo{ href: "" }
    / mini logo for sidebar mini 50x50 pixels
    %span.logo-mini
      %b
        A
      dm
    / logo for regular state and mobile devices
    %span.logo-lg
      %b
        %img{ src: "/assets/admin.png"}
          Boxtrip
      Admin
  / Header Navbar
  %nav.navbar.navbar-static-top{ role: "navigation" }
    / Sidebar toggle button
    %a.sidebar-toggle{"data-toggle" => "offcanvas", href: "#", role: "button"}
      %span.sr-only Toggle navigation
    / Navbar Right Menu
    .navbar-custom-menu
      %ul.nav.navbar-nav
        / User Account Menu
        %li.dropdown.user.user-menu
          / Menu Toggle Button
          %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
            / The user image in the navbar
            %img.user-image{ alt: "User Image", src: "/assets/dashboard/truck_128X128.png" }
            / hidden-xs hides the username on small devices so only the image appears.
            %span.hidden-xs Administrator
          %ul.dropdown-menu
            / The user image in the menu
            %li.user-header
              %img.img-circle{ alt: "User Image", src: "/assets/dashboard/truck_128X128.png" }
              %p
                Administrador
                %small Miembro desde Mayo del 2015
            / Menu Body
            %li.user-body
              .col-xs-12.text-center
                %a{ href: "#" }
                  Reservaciones realizas
                  %label.label.label-info
                    = @tailoreds.count + @yolos.count
            / Menu Footer
            %li.user-footer
              .pull-right
                = link_to 'Cerrar sesión', destroy_admin_session_path, method: :delete, class: "btn btn-danger btn-flat btn-logout"
                -# %a.btn.btn-danger.btn-flat.btn-logout{ href: destroy_admin_session_path, method: :delete } Cerrar sesión

app/views/admin/dashboard/partials/_sidebar.html.haml
%aside.main-sidebar
  %section.sidebar
    .user-panel
      .pull-left.image
        %img.img-circle{alt: "User Image", src: "/assets/dashboard/truck_128X128.png"}
      .pull-left.info
        %p Administrador
        / Status
        %a{href: "#"}
          %i.fa.fa-star.text-info
          Administrador
    %ul.sidebar-menu
      %li.header MENÚ DE ADMINISTRADOR
      %li
        %a{"data-toggle" => "tab", href: "#admin_content", role: "tab"}
          %i.fa.fa-users
          %span Registros